version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=ubamtol
      - POSTGRES_PASSWORD=dbdlswns98.
      - POSTGRES_DB=DUC_Tech_Community
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
